In [ ]:
import numpy as np
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [ ]:
output

array([[0.94244913],
       [0.0809753 ],
       [0.95396908]])

In [ ]:
import tensorflow as tf
print("TensorFlow version",tf.__version__)

TensorFlow version 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.99304813, -0.8584403 , -0.7589099 , -0.07716011,  0.7433611 ,
        -0.10309228, -0.78627497, -0.5460927 , -0.36007553, -0.15056491]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.04757958, 0.05443523, 0.06013199, 0.11890105, 0.27010557,
        0.11585733, 0.05850878, 0.0743928 , 0.08960187, 0.11048578]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.1553957

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2928 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1406 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1060 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0884 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0741 - accuracy: 0.9774
